# Generated by Django 5.2.16 on 2026-07-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companynews',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='companynews',
            name='url',
            field=models.TextField(verbose_name='新聞連結 URL'),
        ),
    ]
