# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(help_text='內部關聯使用的代理鍵 (Surrogate Key)', primary_key=True, serialize=False)),
                ('employee_num', models.CharField(help_text='例如：EMP2026001', max_length=20, unique=True, verbose_name='員工工號')),
                ('first_name', models.CharField(help_text='區分姓與名有利於國際化系統設計', max_length=50, verbose_name='名字')),
                ('last_name', models.CharField(help_text='區分姓與名有利於國際化系統設計', max_length=50, verbose_name='姓氏')),
                ('national_id', models.CharField(help_text='機敏資料', max_length=20, unique=True, verbose_name='身分證字號 / 護照號碼')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '非二元')], default=0, help_text='0: 未知, 1: 男, 2: 女, 3: 非二元', verbose_name='性別')),
                ('birth_date', models.DateField(help_text='計算員工法定年齡與生日福利', verbose_name='出生日期')),
                ('email', models.EmailField(help_text='用於系統登入與公務通知', max_length=100, unique=True, verbose_name='公司電子信箱')),
                ('personal_email', models.EmailField(blank=True, help_text='離職聯絡或緊急狀況備用', max_length=100, null=True, verbose_name='個人電子信箱')),
                ('phone', models.CharField(help_text='純數字存放', max_length=20, verbose_name='行動電話')),
                ('department_id', models.IntegerField(blank=True, help_text='關聯至部門表 (departments.id)', null=True, verbose_name='所屬部門 ID')),
                ('job_title_id', models.IntegerField(blank=True, help_text='關聯至職稱表 (job_titles.id)', null=True, verbose_name='職務 / 職稱 ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '離職'), (1, '在職'), (2, '留職停薪'), (3, '試用期')], default=1, help_text='0: 離職, 1: 在職, 2: 留職停薪, 3: 試用期', verbose_name='員工狀態')),
                ('hire_date', models.DateField(help_text='計算年資與特休假特權的基準', verbose_name='到職日期')),
                ('termination_date', models.DateField(blank=True, help_text='員工離職時填入，在職時為 NULL', null=True, verbose_name='離職日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='資料建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='資料更新時間')),
                ('manager', models.ForeignKey(blank=True, db_column='manager_id', help_text='自我關聯建立組織樹', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='直屬主管 ID')),
            ],
            options={
                'verbose_name': '員工主資料表',
                'verbose_name_plural': '員工主資料表',
                'db_table': 'employees',
                'ordering': ['-id'],
            },
        ),
    ]
