# Generated by Django 5.2.16 on 2026-07-27 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseManagerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_manage_db_tables', '可以管理資料庫與表單資料 (DataTables & 帳號切換)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('stock_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='股票代碼')),
                ('tax_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='統一編號')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('spokesperson', models.CharField(blank=True, max_length=50, null=True, verbose_name='發言人')),
                ('eng_short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文簡稱')),
                ('deputy_spokesperson', models.CharField(blank=True, max_length=50, null=True, verbose_name='代理發言人')),
                ('establishment_date', models.DateField(blank=True, null=True, verbose_name='成立時間')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='總機電話')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='掛牌日期')),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='傳真號碼')),
                ('industry_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='產業類別')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司網站')),
                ('chairman', models.CharField(blank=True, max_length=50, null=True, verbose_name='董事長')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='電子郵件')),
                ('general_manager', models.CharField(blank=True, max_length=50, null=True, verbose_name='總經理')),
                ('stock_transfer_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='股務代理')),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='股本(元)')),
                ('auditor', models.CharField(blank=True, max_length=100, null=True, verbose_name='簽證會計師')),
                ('issued_shares', models.BigIntegerField(blank=True, null=True, verbose_name='已發行普通股數')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
                ('market_cap_millions', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='市值(百萬)')),
                ('market_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='市場別')),
                ('insider_holding_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='董監持股比例(%)')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='所屬集團')),
                ('main_business', models.TextField(blank=True, null=True, verbose_name='主要經營業務')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '公司基本資料',
                'verbose_name_plural': '公司基本資料',
                'db_table': 'company_profile',
            },
        ),
        migrations.CreateModel(
            name='StockScheduleList',
            fields=[
                ('stock_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='股票代碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '排程更新清單',
                'verbose_name_plural': '排程更新清單',
                'db_table': 'stock_schedule_list',
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('news_type', models.CharField(max_length=100, verbose_name='類型')),
                ('title', models.TextField(verbose_name='標題')),
                ('url', models.CharField(max_length=500, verbose_name='新聞連結 URL')),
                ('publisher', models.CharField(blank=True, max_length=500, null=True, verbose_name='發布來源')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='內文摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('stock', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='news', to='core.companyprofile', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司新聞與個股公告',
                'verbose_name_plural': '公司新聞與個股公告',
                'db_table': 'company_news',
                'unique_together': {('stock', 'url')},
            },
        ),
        migrations.CreateModel(
            name='CompanyCalendar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50, verbose_name='事件類型')),
                ('event_date', models.DateField(verbose_name='事件日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='補充說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('stock', models.ForeignKey(db_column='stock_id', on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.companyprofile', verbose_name='公司')),
            ],
            options={
                'verbose_name': '公司行事曆',
                'verbose_name_plural': '公司行事曆',
                'db_table': 'company_calendar',
                'unique_together': {('stock', 'event_type', 'event_date')},
            },
        ),
    ]
